---
- name: Hyprland
  block:
  - name: Hyprland - Install (including deps)
    pacman:
      name:
        - hyprland
        - hypridle
        - hyprlock
        - hyprpicker
        - nvidia-dkms
        - nvidia-utils
        - egl-wayland
        - linux-headers
        - glfw-wayland
        - gtk3
        - pipewire
        - pipewire-alsa
        - pipewire-pulse
        - pavucontrol
        - pamixer
        - wireplumber
        - grim
        - slurp
        - polkit
        - rtkit
        - xdg-desktop-portal-hyprland
        - xdg-desktop-portal-gtk
        - mako
        - qt5-wayland
        - qt6-wayland
        - wofi
        - waybar
        - wl-clipboard
        - cliphist
        - greetd
        - greetd-regreet
        - cage
        - wev
      state: present

  - name: Hyprland - Ensure NVIDIA config directory exists
    file:
      path: /etc/modprobe.d
      recurse: true
      state: directory

  - name: Hyprland - Copy NVIDIA config
    copy:
      src: nvidia.conf
      dest: /etc/modprobe.d

  - name: Hyprland - Enable seatd
    ansible.builtin.systemd_service:
      name: seatd
      enabled: true

  - name: Hyprland - Enable greetd
    ansible.builtin.systemd_service:
      name: greetd
      enabled: true

  - name: Hyprland - Enable nvidia-suspend
    ansible.builtin.systemd_service:
      name: nvidia-suspend
      enabled: true

  - name: Hyprland - Enable nvidia-hibernate
    ansible.builtin.systemd_service:
      name: nvidia-hibernate
      enabled: true


  - name: Hyprland - Enable nvidia-resume
    ansible.builtin.systemd_service:
      name: nvidia-resume
      enabled: true

  - name: Hyprland - Add user to seat group
    ansible.builtin.command:
      cmd: "usermod -aG seat {{ local_user }}"

  - name: Hyprland - Add greeter to seat & video groups
    ansible.builtin.command:
      cmd: "usermod -aG seat,video greeter"

  - name: Hyprland - Add user to input group
    ansible.builtin.command:
      cmd: "usermod -aG input {{ local_user }}"

- name: Grimblast (screenshots)
  block:
  - name: Grimblast - Clone repo
    ansible.builtin.git:
      repo: https://github.com/hyprwm/contrib.git
      dest: "/usr/local/hyprwm"
      force: true
  - name: Grimblast - make
    ansible.builtin.shell: |
      make install
    args:
      chdir: "/usr/local/hyprwm/grimblast"
