---
- name: Hyprland
  block:
  - name: Hyprland - Install (including deps)
    pacman:
      name:
        - hyprland
        - hypridle
        - hyprlock
        - nvidia-dkms
        - nvidia-utils
        - egl-wayland
        - linux-headers
        - glfw-wayland
        - gtk3
        - pipewire
        - wireplumber
        - polkit
        - rtkit
        - xdg-desktop-portal-hyprland
        - xdg-desktop-portal-gtk
        - mako
        - qt5-wayland
        - qt6-wayland
        - wofi
        - waybar
        - wl-clipboard
        - cliphist
      state: present

  - name: Hyprland - Ensure NVIDIA config directory exists
    file:
      path: /etc/modprobe.d
      recurse: true
      state: directory

  - name: Hyprland - Copy NVIDIA config
    copy:
      src: nvidia.conf
      dest: /etc/modprobe.d

  - name: Hyprland - Enable seatd
    ansible.builtin.systemd_service:
      name: seatd
      enabled: true

  - name: Hyprland - Add user to seat group
    ansible.builtin.command:
      cmd: "usermod -aG seat {{ local_user }}"

  - name: Hyprland - Add user to input group
    ansible.builtin.command:
      cmd: "usermod -aG input {{ local_user }}"
