---
- name: Pacman Update
  ansible.builtin.pacman:
    update_cache: true
    upgrade: true

- name: Set up workspace folder
  become: true
  become_user: "{{ local_user }}"
  ansible.builtin.file:
    path: "{{ workspace.path }}"
    state: directory
